# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-30 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaincontent', '0009_item_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_deleted',
            field=models.BooleanField(default=True),
        ),
    ]
